version: '3'

services:

  bot:
    build:
      context: .
      dockerfile: backend-p2p/Dockerfile
    restart: unless-stopped
    ports:
      - "8001:8001"
    networks:
      - app-network

  db:
    image: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge