"""create models(user, model)

Revision ID: 38666f67f94b
Revises: 
Create Date: 2023-05-24 14:31:47.053690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38666f67f94b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
    sa.Column('idx', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('idx')
    )
    op.create_table('movies',
    sa.Column('idx', sa.BigInteger(), nullable=False),
    sa.Column('href', sa.String(length=1024), nullable=True),
    sa.Column('genres', sa.String(length=1024), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('voiced_by', sa.String(length=1024), nullable=True),
    sa.Column('year', sa.String(length=1024), nullable=True),
    sa.Column('rate', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('preview', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('idx')
    )
    op.create_table('users',
    sa.Column('idx', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('setup_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('idx')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('movies')
    op.drop_table('genres')
    # ### end Alembic commands ###
